version: '2'

networks:
  default:
    external:
      name: seedbox

services:
  consul:
    container_name: consul
    image: consul
    environment:
      - SERVICE_IGNORE=true
    ports:
      - 127.0.0.1:8500:8500
    command: agent -server -bootstrap -node seedbox.example.com -client=0.0.0.0 -ui

  registrator:
    container_name: registrator
    image: gliderlabs/registrator
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  consul-template:
    container_name: consul-template
    image: blackillzone/consul-template:1.11
    volumes:
      - ./consul-templates:/templates
      - ./data/nginx/conf:/conf/nginx
      - ./data/muximux/config/www/muximux:/conf/muximux
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: -wait=5s -retry 30s -consul consul:8500 -template "/templates/default.ctmpl:/conf/nginx/default.conf:docker kill -s HUP nginx" -template "/templates/settings.ctmpl:/conf/muximux/settings.ini.php:docker restart muximux"
    depends_on:
      - nginx

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - 127.0.0.1:8989:8989
    environment:
      - SERVICE_NAME=sonarr
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - ./data/sonarr/config:/config
      - ./data/series:/tv
      - ./data/transmission/series/.torrent:/torrents
      - ./data/transmission/series:/downloads
    depends_on:
      - consul

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    ports:
      - 127.0.0.1:5050:5050
    environment:
      - SERVICE_NAME=couchpotato
      - TZ=Europe/Paris
    volumes:
      - ./data/couchpotato/config:/config
      - ./data/movies:/movies
      - ./data/transmission/movies/.torrent:/torrents
      - ./data/transmission/movies:/downloads
    depends_on:
      - consul

  plex:
    container_name: plex
    image: linuxserver/plex
    ports:
      - 127.0.0.1:32400:32400
    environment:
      - SERVICE_32400_NAME=plex
      - SERVICE_32469_IGNORE=true
      - SERVICE_1900_IGNORE=true
      - SERVICE_5353_IGNORE=true
      - VERSION=public
      - TZ=Europe/Paris
    volumes:
      - ./data/plex/config:/config
      - ./data/series:/data/tvshows
      - ./data/movies:/data/movies
    depends_on:
      - consul

  muximux:
    container_name: muximux
    image: linuxserver/muximux
    ports:
      - 127.0.0.1:8080:80
    environment:
      - SERVICE_80_NAME=muximux
      - SERVICE_443_IGNORE=true
      - TZ=Europe/Paris
    volumes:
      - ./data/muximux/config:/config
    depends_on:
      - consul

  glances:
    container_name: glances
    image: docker.io/nicolargo/glances
    ports:
      - 127.0.0.1:61208:61208
    environment:
      - SERVICE_61208_NAME=glances
      - SERVICE_61209_IGNORE=true
      - GLANCES_OPT=-w
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx

  transmission-series:
    container_name: transmission-series
    image: linuxserver/transmission
    ports:
      - 127.0.0.1:9091:9091
    environment:
      - SERVICE_9091_NAME=transmission-series
      - SERVICE_51413_IGNORE=true
      - TZ=Europe/Paris
    volumes:
      - ./data/transmission/series/.config:/config
      - ./data/transmission/series/.torrent:/watch
      - ./data/transmission/series:/downloads
    depends_on:
      - nginx

  transmission-movies:
    container_name: transmission-movies
    image: linuxserver/transmission
    ports:
      - 127.0.0.1:9092:9091
    environment:
      - SERVICE_9091_NAME=transmission-movies
      - SERVICE_51413_IGNORE=true
      - TZ=Europe/Paris
    volumes:
      - ./data/transmission/movies/.config:/config
      - ./data/transmission/movies/.torrent:/watch
      - ./data/transmission/movies:/downloads
    depends_on:
      - nginx
